Project BulletBook {
    database_type: 'PostgreSQL'
    Note: '''
    # Project Tracking Database
    '''
}

Table profiles as users {
    id uuid [pk]
    username text
    email text
    avatar text
}

Table technologies {
    id uuid [pk]
    name text
    icon text
    description text
    category text
}

Table tech_references {
    id uuid [pk]
    technology_id uuid [ref: > technologies.id]
    title text
    url text
}

Table projects {
    id int [pk, increment]
    user_id int [ref: > users.id]
    name varchar
    description text
}

Table project_images {
    id int [pk, increment]
    project_id int [ref: > projects.id]
    url varchar
}

Table project_urls {
    id int [pk, increment]
    project_id int [ref: > projects.id]
    live varchar
    github varchar
}

Table projcet_bullets {
    id int [pk, increment]
    project_id int [ref: > projects.id]
    title varchar
    text varchar
}

Table bullet_techs {
    id int [pk, increment]
    bullet_id int [ref: > projcet_bullets.id]
    tech_id int [ref: > technologies.id]
}